name: Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Push
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: 'build'
      - name: Setup Node 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install Python2
        run: sudo apt install python2
      - name: Install Dependencies
        run: npm ci
      - name: Build
        run: npm run prepublish
#      - name: Config Git
#        run: |
#          git config --global user.email "crossscar2@outlook.com"
#          git config --global user.name "CommanderGL"
#      - name: Commit Files to Git
#        run: |
#          git add * || true
#          git commit -m "Build: ({sha}) {msg}"
      - name: Push
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: build
          FOLDER: .
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: "Build: ({sha}) {msg}"
